# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-TCG
version:      0.000
version_from: lib/Time/TCG.pm
installdirs:  site
requires:
    Math::BigRat:                  0.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
